### ISSUE TITLE
Question about Image Level and Patient Level Accuracy

### ISSUE THREAD

**Issue by alibalapour** [prakashchhipa/Magnification-Prior-Self-Supervised-Method#1]
Can you explain about Image Level and Patient Level Accuracy you mentioned in the paper? I searched about them but I couldn't get the exact meaning of them.

**Comment by prakashchhipa** [comment]
[Edited]
Hi,
Image Level Accuracy is nothing but as typical accuracy term and patient level accuracy is where accuracy is measure for each patient then mean value is calculated on patients.
For more clarity, please check the the paper "Data Augmentation for Histopathological Images Based on Gaussian-Laplacian Pyramid Blending" on BreakHis Dataset.

**Comment by alibalapour** [comment]
Does it mean that the image recognition rate or Image-Level Accuracy is the recall in binary classification task? Am I right?

**Comment by prakashchhipa** [comment]
> Does it mean that the image recognition rate or Image-Level Accuracy is the recall in binary classification task? Am I right?

I have edited answer above with correct paper title for reference.

**Comment by prakashchhipa** [comment]
> Does it mean that the image recognition rate or Image-Level Accuracy is the recall in binary classification task? Am I right?

Just to clarify further, from the evaluation term "Recognition Rate" which is also been used in many research work- Let N_all be the number of cancer images of the test set. If the system classifies correctly N_rec cancer images, then Recognition Rate is N_rec/N_all. Basically, Recognition Rate (Recall of cancer class) term only focuses on correct identification on cancer class image correct identification. If it is calculated for each patient and then mean value over patient is taken then it becomes Patient Recognition Rate. Term Recognition Rate is more popular in medical field during classification tasks where from machine learning perspective, accuracy is more used which consider the correctness of classification for both classes - cancer  and non-cancer. It is possible to have higher values if recognition rate is calculated for the method proposed in the this paper.

**Comment by alibalapour** [comment]
I got it. 
Thank you
