### ISSUE TITLE
Code Run

### ISSUE THREAD

**Issue by keremyucel83** [prakashchhipa/Magnification-Prior-Self-Supervised-Method#2]
Hello, I am a master student and working on your code as part of my class in deep learning and tried tools like colab and visual studio code however they both did not work because of the structure I mean split py files. Could you please help me to find the best way to run the code? like which tool I should use?

**Comment by prakashchhipa** [comment]
Hi, the project work is carried out on Visual studio and it is well suitable for this. Data processing work can be treated as indvidual work so you can run each individual python file for their defined purpose from data processing to splitting for each specific dataset. Adapt it for the correct storage path and format.
