### ISSUE TITLE
".ob" file in prepare_metadata_bach.py

### ISSUE THREAD

**Issue by Omekaago101** [prakashchhipa/Magnification-Prior-Self-Supervised-Method#3]
In the prepare_metadata_bach.py, you opened a ".ob" file. How is the file generated?

**Comment by prakashchhipa** [comment]
In code, metadata details in first being written on .ob file using pickle and same file were opened to to verify if file data is readable. I don't put any specific requirement to use .ob file, it could be some other type file as well.

**Comment by Omekaago101** [comment]
In the code, the ".ob" file is being read from a particular directory. Which means it was created earlier somewhere in the code. I want to know how to generate that file or in any other format. Because it is needed when you want to run the finetune_bach.py
